GET     http://localhost:3000/categories/

###
GET     http://localhost:3000/categories/1

###
POST    http://localhost:3000/categories/
Content-Type: application/json

{
    "cate": "samsung"
}

###
PATCH   http://localhost:3000/categories/1
Content-Type: application/json

{
    "cate": "phones "
}

###
DELETE  http://localhost:3000/categories/1